version: '3.8'

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-controller
    hostname: controller
    privileged: true
    volumes:
      - ./slurm:/slurm
    networks:
      hpc-net:
        ipv4_address: 10.0.0.2
    command: >
      bash -c "sleep infinity"

  compute1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-compute1
    hostname: compute1
    privileged: true
    volumes:
      - ./slurm:/slurm
    networks:
      hpc-net:
        ipv4_address: 10.0.0.3
    command: >
      bash -c "sleep infinity"

  compute2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-compute2
    hostname: compute2
    privileged: true
    volumes:
      - ./slurm:/slurm
    networks:
      hpc-net:
        ipv4_address: 10.0.0.4
    command: >
      bash -c "sleep infinity"

networks:
  hpc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
