services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-controller
    hostname: controller
    privileged: true
    volumes:
      - ./slurm:/slurm
      - ./cluster-share:/opt/shared
    networks:
      hpc-net:
        ipv4_address: 10.0.0.2
    command: >
      bash -c "
        cp /slurm/* /etc/slurm &&
        cp /slurm/munge.key /etc/munge/munge.key &&
        chmod 600 /etc/munge/munge.key &&
        /etc/init.d/munge start &&
        mkdir -p /var/spool/slurm/ctld &&
        slurmctld -vvv &&
        tail -f /dev/null"

  compute1:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-compute1
    hostname: compute1
    privileged: true
    volumes:
      - ./slurm:/slurm
      - ./cluster-share:/opt/shared
    networks:
      hpc-net:
        ipv4_address: 10.0.0.3
    command: >
      bash -c "
        cp /slurm/* /etc/slurm &&
        cp /slurm/munge.key /etc/munge/munge.key &&
        chmod 600 /etc/munge/munge.key &&
        /etc/init.d/munge start &&
        mkdir -p /var/spool/slurm/d &&
        slurmd -vvv &&
        tail -f /dev/null"

  compute2:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: slurm-compute2
    hostname: compute2
    privileged: true
    volumes:
      - ./slurm:/slurm
      - ./cluster-share:/opt/shared
    networks:
      hpc-net:
        ipv4_address: 10.0.0.4
    command: >
      bash -c "
        cp /slurm/* /etc/slurm &&
        cp /slurm/munge.key /etc/munge/munge.key &&
        chmod 600 /etc/munge/munge.key &&
        /etc/init.d/munge start &&
        mkdir -p /var/spool/slurm/d &&
        slurmd -vvv &&
        tail -f /dev/null"

networks:
  hpc-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
