Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "node\#{i}" do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.hostname = "node\#{i}"
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
end
