name: HPC Lab Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ansible Lint
        run: sudo apt-get install -y ansible-lint && ansible-lint playbooks/
